version: "3.8"

services:
  jalcode-backend:
    build: .
    container_name: jalcode-api-server
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./uploads:/app/uploads
    env_file:
      - .env
    depends_on:
      - jalcode-redis
    networks:
      - jalcode-network

  jalcode-redis:
    image: redis:alpine
    container_name: jalcode-redis-server
    restart: always
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - jalcode-network

networks:
  jalcode-network:
    driver: bridge

# VOLUME UNTUK REDIS
volumes:
  redis-data:
