basePath: /
definitions:
  dto.ClientRequest:
    properties:
      address:
        type: string
      company:
        type: string
      email:
        type: string
      name:
        type: string
      phone:
        type: string
    required:
    - company
    - name
    type: object
  dto.LoginRequest:
    properties:
      email:
        type: string
      password:
        type: string
    required:
    - email
    - password
    type: object
  dto.MenteeRequest:
    properties:
      email:
        type: string
      mentor_id:
        type: integer
      name:
        type: string
      program:
        type: string
      status:
        type: string
    required:
    - mentor_id
    - name
    - program
    - status
    type: object
  dto.ProjectRequest:
    properties:
      category:
        type: string
      client_id:
        type: integer
      status:
        type: string
      team_member_id:
        type: integer
      title:
        type: string
    required:
    - category
    - status
    - team_member_id
    - title
    type: object
  dto.RegisterRequest:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        minLength: 6
        type: string
      role:
        type: string
    required:
    - email
    - name
    - password
    - role
    type: object
  dto.TeamMemberRequest:
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
      role:
        type: string
    required:
    - email
    - name
    - role
    type: object
host: localhost:8080
info:
  contact: {}
  description: REST API terpusat untuk sistem manajemen Tim dan Proyek Klien Jalcode.
  title: Jalcode API Documentation
  version: "1.0"
paths:
  /api/auth/login:
    post:
      consumes:
      - application/json
      description: Melakukan autentikasi menggunakan email dan password untuk mendapatkan
        token JWT
      parameters:
      - description: Data Login
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.LoginRequest'
      produces:
      - application/json
      responses:
        "200":
          description: Berhasil login & mendapat token
          schema:
            additionalProperties: true
            type: object
      summary: Login pengguna
      tags:
      - Auth
  /api/auth/register:
    post:
      consumes:
      - application/json
      description: Mendaftarkan anggota tim baru ke dalam sistem
      parameters:
      - description: Data Registrasi
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.RegisterRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Register member baru
      tags:
      - Auth
  /api/clients:
    get:
      description: Menampilkan daftar semua klien beserta proyek yang mereka miliki
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Ambil semua data klien
      tags:
      - Clients
    post:
      consumes:
      - application/json
      description: Menambahkan data perusahaan klien ke database
      parameters:
      - description: Data Klien
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.ClientRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Tambah klien baru
      tags:
      - Clients
  /api/clients/{id}:
    delete:
      description: Menghapus perusahaan klien dari database berdasarkan ID
      parameters:
      - description: ID Klien
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Hapus data klien
      tags:
      - Clients
    put:
      consumes:
      - application/json
      description: Memperbarui informasi klien berdasarkan ID
      parameters:
      - description: ID Klien
        in: path
        name: id
        required: true
        type: string
      - description: Data Update
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.ClientRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Update data klien
      tags:
      - Clients
  /api/mentees:
    get:
      description: Menampilkan daftar semua mentee beserta mentornya
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Ambil semua data peserta didik
      tags:
      - Mentorship
    post:
      consumes:
      - application/json
      description: Mendaftarkan mentee baru ke dalam program mentorship
      parameters:
      - description: Data Mentee
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.MenteeRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Tambah peserta didik baru
      tags:
      - Mentorship
  /api/mentees/{id}:
    delete:
      description: Menghapus mentee dari sistem
      parameters:
      - description: ID Mentee
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Hapus data peserta didik
      tags:
      - Mentorship
    put:
      consumes:
      - application/json
      description: Memperbarui informasi mentee berdasarkan ID
      parameters:
      - description: ID Mentee
        in: path
        name: id
        required: true
        type: string
      - description: Data Update
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.MenteeRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Update data peserta didik
      tags:
      - Mentorship
  /api/projects/:
    get:
      description: Mendapatkan daftar semua proyek beserta PIC dan Klien
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Ambil semua data proyek
      tags:
      - Projects
    post:
      consumes:
      - application/json
      description: Menambahkan proyek dan menugaskannya ke anggota tim
      parameters:
      - description: Data Proyek
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.ProjectRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Tambah proyek baru
      tags:
      - Projects
  /api/projects/{id}:
    delete:
      description: Menghapus proyek dari database berdasarkan ID
      parameters:
      - description: ID Proyek
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Hapus proyek
      tags:
      - Projects
    put:
      consumes:
      - application/json
      description: Memperbarui informasi proyek berdasarkan ID
      parameters:
      - description: ID Proyek
        in: path
        name: id
        required: true
        type: string
      - description: Data Update
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.ProjectRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Update data proyek
      tags:
      - Projects
  /api/teams:
    post:
      consumes:
      - application/json
      description: Mendaftarkan anggota tim baru ke dalam sistem
      parameters:
      - description: Data Anggota Tim
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.TeamMemberRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Menambahkan anggota tim baru
      tags:
      - Teams
  /api/teams/:
    get:
      description: Mendapatkan daftar lengkap semua tim beserta role-nya
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Mengambil semua data anggota tim
      tags:
      - Teams
  /api/teams/{id}:
    delete:
      description: Menghapus data anggota tim secara permanen berdasarkan ID
      parameters:
      - description: ID Anggota Tim
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Menghapus anggota tim
      tags:
      - Teams
    put:
      consumes:
      - application/json
      description: Memperbarui nama, role, email, atau password anggota tim berdasarkan
        ID
      parameters:
      - description: ID Anggota Tim
        in: path
        name: id
        required: true
        type: string
      - description: Data Update
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/dto.TeamMemberRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      security:
      - BearerAuth: []
      summary: Mengedit data anggota tim
      tags:
      - Teams
securityDefinitions:
  BearerAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
