name: Deploy Backend to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Eksekusi Perintah di VPS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          password: ${{ secrets.VPS_PASSWORD }}
          port: 22
          script: |
            # MANTRA BARU: Hentikan robot seketika jika ada error sekecil apapun!
            set -e 

            echo "Memulai proses Deployment Otomatis 🚀"
            cd /root/jalcode-workspace

            # MANTRA BARU: Sinkronisasi Paksa! Abaikan konflik, ikuti 100% kode dari GitHub
            git fetch origin
            git reset --hard origin/main

            # Masuk ke ruang mesin
            cd backend

            echo "Merakit ulang Docker..."
            docker compose down
            docker compose up -d --build

            echo "Deployment Berhasil Mutlak! API sudah terupdate ✅"
